---
version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt -y update
      - apt -y install docker.io unzip
      # Installing EKSCTL
      - ARCH=amd64
      - PLATFORM=$(uname -s)_$ARCH
      - curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
      - curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
      - tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
      - mv /tmp/eksctl /usr/local/bin
      # Installing KUBECTL
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - chmod +x /usr/local/bin/kubectl
      # Installing Terraform
      - apt-get update && apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update
      - apt-get install -y terraform
      # Start Docker
      #- systemctl start docker

  pre_build:
    commands:
      - echo "Configuring AWS CLI"
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region ap-south-1
      - aws eks update-kubeconfig --name Ayushmaan-EKS --region ap-south-1
      - kubectl label node $(kubectl get nodes --no-headers | awk '{print $1}') worker=worker1
      - echo "Logging in to Docker Hub"
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Applying Terraform configuration..."
      - terraform apply --auto-approve
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f hello.yaml
      - kubectl apply -f service.yaml
