version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
