---
version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt -y update
      # Installing Terraform
      - apt-get update && apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update
      - apt-get install -y terraform
      # Start Docker
      #- systemctl start docker

  pre_build:
    commands:
      - echo "Configuring AWS CLI"
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region ap-south-1
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Applying Terraform configuration..."
      - terraform apply --auto-approve
